#!/bin/sh
set -e

# Hook for building live images
#
# This script is run in the built chroot after all packages are installed,
# before it is packed into a squashfs. This is where you can apply extra tweaks
# to the live system.

# This seems to be the "proper" way to pre-configure the timezone
echo "Europe/Athens" > /etc/timezone
dpkg-reconfigure -f noninteractive tzdata

# Fix the keyboard layout for new users (LP: #975803)
echo "-layout us,gr -option grp:alt_shift_toggle,grp_led:scroll" \
     > /etc/X11/Xkbmap

# Prevent ubiquity-dm from showing and messing up with the keyboard layout
chmod -x /usr/bin/ubiquity-dm
